image: docker:latest

stages:
  - build
  - test
  - push

services:
  - docker:dind

before_script:
  # docker login asks for the password to be passed through stdin for security
  # we use $CI_JOB_TOKEN here which is a special token provided by GitLab
  - echo -n $CI_REGISTRY_PASSWORD | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY

# build the image and push it on gitlab registry
build:
  stage: build
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHA" .
    # - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHA"
  # only: [] # restrict building to some branches

test:
  image: tmaier/docker-compose:latest
  stage: test
  variables:
    TEST_TIMEOUT_IN_SECONDS: 120
    GIT_SUBMODULE_STRATEGY: recursive
  before_script:
    - apk add --no-cache --update make bash
    - apk add --no-cache --upgrade grep
  script:
    - make tests

# push "latest" image to the registry
build-latest:
  stage: push
  only:
    - master # latest from master only
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:latest" .
    - docker push $CI_REGISTRY_IMAGE:latest

# push "tagged" image to the registry
build-release:
  stage: push
  # only start a release on tags of master (not other branches)
  only:
    - tags # latest from master only
  except:
    - branches
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG" .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
