image: docker:latest

stages:
  - build
  - test
  - release

services:
  - docker:dind

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY # gitlab

build-master:
  stage: build
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:latest" .
    - docker push "$CI_REGISTRY_IMAGE:latest" # push on gitlab
  only:
    - master

build:
  stage: build
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" # push on gitlab
  except:
    - master

release:
  stage: release
  # only start a release on tags of master (not other branches)
  only:
    - tags
  except:
    - branches
  script:
    - docker pull "$CI_REGISTRY_IMAGE"
    - docker tag $CI_REGISTRY_IMAGE $CI_COMMIT_TAG
    - docker push $CI_REGISTRY_IMAGE