version: "3.7"

services:

  rainloop:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: rainloop
    ports:
      - "8001:8888"
    environment:
      - UPLOAD_MAX_SIZE=200M
    volumes:
      - ./rainloop-data:/rainloop/data